### ISSUE TITLE
Error Ubuntu 14

### ISSUE THREAD

**Issue by ghost** [vivocoin/sentinel#1]
```
root@vivo:~/.vivocore/sentinel# SENTINEL_DEBUG=1 ./venv/bin/python bin/sentinel.py
[error]: unable to open database file
Cannot connect to database. Please ensure database service is running and user access is properly configured in 'sentinel.conf'.
```
![snipaste_2017-12-04_10-47-22](https://user-images.githubusercontent.com/18265958/33541540-8faebf5a-d8e0-11e7-9d53-041563f2089f.png)

**Comment by vivocoin** [comment]
Create an empty folder named "database" in your sentinel folder. That's it.  Run "mkdir database" - Alternatively you can refollow the git cloning step in the sentinel guide, the issue has been fixed directly in the repository.

**Comment by ghost** [comment]
It's work. Thank You
