### ISSUE TITLE
Object creation rate exceeded

### ISSUE THREAD

**Issue by fusionfoto** [vivocoin/sentinel#2]
For about a week I've been getting this error with sentinel on vivo:

venv/bin/python bin/sentinel.py
Unable to submit: Object creation rate limit exceeded

My other sentinel/dash based coins don't display this. Before about a week ago, my Vivo MN was running fine.

I've updated to the latest sentinel with the same results. Any ideas?

thanks

**Comment by fusionfoto** [comment]
Changing the timing of my cron job does not seem to serve any effect, and if I set it too long, my node times out.

**Comment by hunbalazs** [comment]
This is a cosmetic issue, only happens very rarely and won't affect normal operation.
