### ISSUE TITLE
Cannot connect to vivod.

### ISSUE THREAD

**Issue by MoreMeg** [vivocoin/sentinel#3]
After I run: venv/bin/python bin/sentinel.py
I get error: -342: non-JSON HTTP response with '401 Unauthorized' from server
Cannot connect to vivod. Please ensure vivod is running and the JSONRPC port is open to Sentinel.

In sentinel.conf I have uncommented line vivo_conf=/root/.vivocore/vivo.conf

**Comment by hunbalazs** [comment]
In that case I think you also need to provide RPC username and password
